# 该文件用于在 x86_64 开发机上交叉编译 Orange Pi AI Pro 等 aarch64 Linux 目标。
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(AARCH64_TOOLCHAIN_PREFIX "aarch64-linux-gnu" CACHE STRING "aarch64 cross compiler prefix")

find_program(AARCH64_C_COMPILER "${AARCH64_TOOLCHAIN_PREFIX}-gcc")
find_program(AARCH64_CXX_COMPILER "${AARCH64_TOOLCHAIN_PREFIX}-g++")

if(NOT AARCH64_C_COMPILER)
    message(FATAL_ERROR "cannot find ${AARCH64_TOOLCHAIN_PREFIX}-gcc")
endif()

if(NOT AARCH64_CXX_COMPILER)
    message(FATAL_ERROR "cannot find ${AARCH64_TOOLCHAIN_PREFIX}-g++")
endif()

set(CMAKE_C_COMPILER "${AARCH64_C_COMPILER}")
set(CMAKE_CXX_COMPILER "${AARCH64_CXX_COMPILER}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
